#!/usr/bin/env php
<?php

namespace app;

use app\Protected\Core\AppProtectedsCommands\CreateEntity;
use Symfony\Component\Console\Application;

require __DIR__ . '/vendor/autoload.php';

/**
 * Start the console application.
 */
$app = new Application('TWIMM CONSOLE', '1.0.0');
//$app->setDefaultCommand("hello");

$app->add(new CreateEntity());
// $app->add(new AnotherCommand());

$app->run();
